### ISSUE TITLE
只能进入登陆界面

### ISSUE THREAD

**Issue by Char1024** [coffee0202/Theater#1]
你好，为什么我输入用户名和密码之后程序就关闭了。

**Comment by coffee0202** [comment]
这是来自QQ邮箱的自动回复邮件。 您好，应数【梁光飞】已经收到您的邮件！

**Comment by Kwongfei** [comment]
我不太明白为什么会这样。 因为在我的电脑里无论是用户端还是管理端都可以进入。 可以尝试整个原始文件下载下来后，在".\Theater\bin\Debug" 文件中找到"Theater.exe"，点击尝试运行。

管理界面的话，账号和密码都是admin。

用户界面的话，可以先自行注册一个账号。

**Comment by Char1024** [comment]
请问怎么进入管理界面呢？

**Comment by coffee0202** [comment]
这是来自QQ邮箱的自动回复邮件。 您好，已经收到您的邮件，感谢来信！

**Comment by Kwongfei** [comment]
建议详细阅读README文档。用户和管理员共用一个登录界面！ 在登录界面，输入
账号: admin
和
密码: admin
即可进入管理端。

**Comment by Char1024** [comment]
噢噢，学长也是华工数院的吗，我在做数据库的课设。

**Comment by Kwongfei** [comment]
是的，加油！XD
